version: "2"
services:
  strihani:
    image: node
    restart: always
    working_dir: /work
    #command: [ 'node',  '_run_server.js' ]
    command: ['bash', '-c', 'while true; do sleep 10; done']
    expose:
    - 8080
    volumes:
    - .:/work
    labels:
      # enable traefik processing
      - "traefik.enable=true"
      # secure traefik internal service - API
      - "traefik.http.routers.strih.entrypoints=websecure"
      - "traefik.http.routers.strih.rule=Host(`strihani.pacov.city`)"
      - "traefik.http.routers.strih.tls=true"
      - "traefik.http.routers.strih.tls.certresolver=letsencrypt"

networks: 
  default:
    external:
        name: proxy  
        