version: "2"
services:
  strihani:
    image: node
    restart: always
    command: node _run_server.js
    expose:
    - 8080
    volumes:
    - .:/work
    labels:
      # enable traefik processing
      - "traefik.enable=true"
      # secure traefik internal service - API
      - "traefik.http.routers.strih.entrypoints=websecure"
      - "traefik.http.routers.strih.rule=Host(`strihani.pacov.city`)"
      - "traefik.http.routers.strih.tls=true"
      - "traefik.http.routers.strih.tls.certresolver=letsencrypt"

networks: 
  default:
    external:
        name: proxy  
        